---
- name: Install Proton Game Compatibility Tools
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Installing Flatpaks
    community.general.flatpak:
      name:
        - org.mozilla.firefox
        - com.github.tchx84.Flatseal
        - net.davidotek.pupgui2
        - net.lutris.lutris
        - net.retrodeck.retrodeck                                                                                                                                                                               
        - io.github.phillipk.boilr
      state: present
      method: system
      remote: flathub
...
