---
- name: Install Discover Flatpaks
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Installing Flatpaks
    community.general.flatpak:
      name:
        - com.github.tchx84.Flatseal
        - net.lutris.lutris
        
      state: present
      method: user
      remote: flathub
...
