---
- name: Add SSH authorized_keys from the list of public keys on GitHub.com
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Set authorized_keys from GitHub public keys
      ansible.posix.authorized_key:
        state: present
        user: deck
        key: "https://github.com/andrewjmetzger.keys"
...
