---
- name: Install Flatpaks
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Add the flathub flatpak repository remote to the system installation
    flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: system
      
  - name: Installing Flatpaks
    community.general.flatpak:
      state: present
      method: system
      remote: flathub
      name:
        - org.mozilla.firefox
        - com.github.tchx84.Flatseal
        - net.lutris.Lutris
...
