---
- name: Download EmuDeck
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create BIOS directory if it does not exist
      ansible.builtin.file:
        path: "{{ lookup('ansible.builtin.env', 'sdcard') }}/Emulation/"
        state: directory
        mode: "0755"

    - name: Download and extract BIOS pack
      ansible.builtin.unarchive:
        src: "https://github.com/Abdess/retroarch_system/releases/download/v20220308/351ELEC-20211122-BIOS.zip"
        dest: "{{ lookup('ansible.builtin.env', 'sdcard') }}/Emulation/"
        remote_src: true

    - name: Download EmuDeck desktop shortcut
      get_url:
        url: "https://www.emudeck.com/EmuDeck.desktop"
        dest: "/home/deck/Desktop/EmuDeck.desktop"
        mode: u+rwx
...